version: '3.4'

services:
  ecommerce-mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: ecommercemssql
    volumes:
      - mssql-server-data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "1q2w3e4r@#"
      ACCEPT_EULA: "Y"   
    ports:
      - "11433:1433" 

  ecommerce-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ecommercerabbitmq
    hostname: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672

  ecommerce-apigateway:
    container_name: ecommerceapigateway
    build:
      context: .
      dockerfile: ./ECommerce.ApiGateway/Dockerfile
    expose:
      - "80"
    ports:
      - "5000:80"    
    depends_on:
      - ecommerce-mssql
      - ecommerce-rabbitmq

  ecommerce-order:
    container_name: ecommerceorder
    build:
      context: .
      dockerfile: ./ECommerce.Order/Dockerfile  
    depends_on:
      - ecommerce-mssql
      - ecommerce-rabbitmq

  ecommerce-catalog:
    container_name: ecommercecatalog
    build:
      context: .
      dockerfile: ./ECommerce.Catalog/Dockerfile  
    depends_on:
      - ecommerce-mssql
      - ecommerce-rabbitmq

  ecommerce-payment:
    container_name: ecommercepayment
    build:
      context: .
      dockerfile: ./ECommerce.Payment/Dockerfile

  ecommerce-gateway:
    container_name: ecommercegateway
    build:
      context: .
      dockerfile: ./ECommerce.Gateway/Dockerfile 

volumes:
  mssql-server-data: