version: '3.4'

services:
  ecommerce-order:
    container_name: ecommerceorder
    build:
      context: .
      dockerfile: ./ECommerce.Order/Dockerfile
    expose:
      - "80"
    ports:
      - "5100:80"    

  ecommerce-catalog:
    container_name: ecommercecatalog
    build:
      context: .
      dockerfile: ./ECommerce.Catalog/Dockerfile
    ports:
      - "5200:80"   

  ecommerce-payment:
    container_name: ecommercepayment
    build:
      context: .
      dockerfile: ./ECommerce.Payment/Dockerfile
    ports:
      - "5300:80"

  ecommerce-gateway:
    container_name: ecommercegateway
    build:
      context: .
      dockerfile: ./ECommerce.Gateway/Dockerfile 
    ports:
        - "5400:80"