version: '3.4'

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql-local
    environment:
      SA_PASSWORD: "1q2w3e4r@#"
      ACCEPT_EULA: "Y"   
    volumes:
      - "./SqlScripts:/usr/src/app/"
    command: 
      - "/usr/src/app/sqlserver-init.sh"
      - "/usr/src/app/migrations.sh"
    ports:
      - "11433:1433" 

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-local
    hostname: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672