// <auto-generated />
using System;
using ECommerce.Catalog.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Catalog.Migrations
{
    [DbContext(typeof(CatalogDBContext))]
    [Migration("20220719122335_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ECommerce.Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("3e6af2f9-f863-4be7-bffc-e5955fe4c2d1"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("57461727-c82d-4ed1-8e95-b9be7909214e"),
                            Description = "Atum",
                            Price = 182.907089399712695m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("cb43d2e5-ddcf-4e88-8236-37b84f89c808"),
                            Description = "Salsicha",
                            Price = 296.857357674779435m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("aa6b6a42-2c0c-4b34-b2d3-256895465025"),
                            Description = "Frango",
                            Price = 175.0055013769145m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("d75999b8-7e48-4b62-adf9-99ac038b7802"),
                            Description = "Bola",
                            Price = 196.933722862309340m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("ba2985d7-fda6-4bc2-b1e5-a61d2928f30d"),
                            Description = "Camiseta",
                            Price = 142.270791389331710m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("1a5249d1-c924-44ef-9212-e824cfa1d4c8"),
                            Description = "Calças",
                            Price = 112.94255232547160m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("30d7855b-3c53-4da0-be13-f6609f703a1e"),
                            Description = "Bicicleta",
                            Price = 495.481408533378680m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("1defafb2-69cc-46f0-9457-c78603bb4e1f"),
                            Description = "Salada",
                            Price = 408.710706872333630m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("b32cb73e-9b62-46af-93be-20f3540ba9f2"),
                            Description = "Carro",
                            Price = 117.829601270890790m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("8b3af8b5-b089-42d2-a587-23286d1e06b3"),
                            Description = "Frango",
                            Price = 419.089636952498705m,
                            Quantity = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
