// <auto-generated />
using System;
using ECommerce.Catalog.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Catalog.Migrations
{
    [DbContext(typeof(CatalogDBContext))]
    partial class CatalogDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ECommerce.Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("144267e5-2051-4c3a-a0a9-01b2ee5fe56c"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d121361b-1d7c-4415-b494-009ee496c205"),
                            Description = "Atum",
                            Price = 429.242828059365260m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("bce1ecc0-ea8e-43a5-8347-691eb973b304"),
                            Description = "Frango",
                            Price = 321.097393587491285m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("3af74a2c-de1c-4deb-bc59-bb54a2544f92"),
                            Description = "Bola",
                            Price = 378.265193931549425m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("011d281a-3743-4419-b218-1da1ec244928"),
                            Description = "Teclado",
                            Price = 190.015841579443160m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("f5649983-33c1-4a4d-9930-e24b651e91db"),
                            Description = "Luvas",
                            Price = 219.134668027185455m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("cb84eaf1-d048-4a9f-b7c5-f69d23a46a75"),
                            Description = "Frango",
                            Price = 210.498992430441215m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("d0b35cc4-f48f-4354-9539-eca93a13a8d7"),
                            Description = "Cadeira",
                            Price = 498.064014599522630m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("06804894-134e-457b-bb2f-c5b67a406ead"),
                            Description = "Peixe",
                            Price = 392.148567140259155m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("9b3d9816-a6cf-47f2-bd4f-16a823adec8c"),
                            Description = "Frango",
                            Price = 111.082403591643380m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("b45e6e1a-d75f-4cac-bda5-c60e6fa6a4c8"),
                            Description = "Peixe",
                            Price = 497.537901027077180m,
                            Quantity = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
